-- Disable RLS on all newly created tables to instantly unblock development and the Storefront

ALTER TABLE brands DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE attributes DISABLE ROW LEVEL SECURITY;
ALTER TABLE attribute_values DISABLE ROW LEVEL SECURITY;
ALTER TABLE sku_attribute_values DISABLE ROW LEVEL SECURITY;
ALTER TABLE sku_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_adjustments DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_serials DISABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE number_sequences DISABLE ROW LEVEL SECURITY;
ALTER TABLE returns DISABLE ROW LEVEL SECURITY;
ALTER TABLE return_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE refunds DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendors DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_items DISABLE ROW LEVEL SECURITY;
